### ISSUE TITLE
Setup Sprint 2

### ISSUE THREAD

**Issue by JoeDLehmanJr** [JoeDLehmanJr/Fall-2022-CPW221-Project-eCom#60]
- [x] Add Issues to the sprint milestone
- [x] Create Milestone Sprint 2
- [x] Create Project eCommerce - Sprint 2 Project
- [x] Create Minor Milestones for the Sprint

**Comment by JoeDLehmanJr** [comment]
closes #60
